// Package models contains generated code for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// AwsAuroraServerless represents a row from 'public.aws_aurora_serverlesses'.
type AwsAuroraServerless struct {
	ID                         string         `json:"id" gorm:"column:id"`                                                 // id
	Regioncode                 AwsRegion      `json:"regioncode" gorm:"column:regioncode"`                                 // regioncode
	Isauroraiooptimizationmode bool           `json:"isauroraiooptimizationmode" gorm:"column:isauroraiooptimizationmode"` // isauroraiooptimizationmode
	Databaseengine             DatabaseEngine `json:"databaseengine" gorm:"column:databaseengine"`                         // databaseengine
	Ondemandprice              StringFloat    `json:"ondemandprice" gorm:"column:ondemandprice"`                           // ondemandprice
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [AwsAuroraServerless] exists in the database.
func (aas *AwsAuroraServerless) Exists() bool {
	return aas._exists
}

// Deleted returns true when the [AwsAuroraServerless] has been marked for deletion
// from the database.
func (aas *AwsAuroraServerless) Deleted() bool {
	return aas._deleted
}

// Insert inserts the [AwsAuroraServerless] to the database.
func (aas *AwsAuroraServerless) Insert(ctx context.Context, db DB) error {
	switch {
	case aas._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case aas._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.aws_aurora_serverlesses (` +
		`id, regioncode, isauroraiooptimizationmode, databaseengine, ondemandprice` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`)`
	// run
	logf(sqlstr, aas.ID, aas.Regioncode, aas.Isauroraiooptimizationmode, aas.Databaseengine, aas.Ondemandprice)
	if _, err := db.ExecContext(ctx, sqlstr, aas.ID, aas.Regioncode, aas.Isauroraiooptimizationmode, aas.Databaseengine, aas.Ondemandprice); err != nil {
		return logerror(err)
	}
	// set exists
	aas._exists = true
	return nil
}

// Update updates a [AwsAuroraServerless] in the database.
func (aas *AwsAuroraServerless) Update(ctx context.Context, db DB) error {
	switch {
	case !aas._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case aas._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.aws_aurora_serverlesses SET ` +
		`regioncode = $1, isauroraiooptimizationmode = $2, databaseengine = $3, ondemandprice = $4 ` +
		`WHERE id = $5`
	// run
	logf(sqlstr, aas.Regioncode, aas.Isauroraiooptimizationmode, aas.Databaseengine, aas.Ondemandprice, aas.ID)
	if _, err := db.ExecContext(ctx, sqlstr, aas.Regioncode, aas.Isauroraiooptimizationmode, aas.Databaseengine, aas.Ondemandprice, aas.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [AwsAuroraServerless] to the database.
func (aas *AwsAuroraServerless) Save(ctx context.Context, db DB) error {
	if aas.Exists() {
		return aas.Update(ctx, db)
	}
	return aas.Insert(ctx, db)
}

// Upsert performs an upsert for [AwsAuroraServerless].
func (aas *AwsAuroraServerless) Upsert(ctx context.Context, db DB) error {
	switch {
	case aas._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.aws_aurora_serverlesses (` +
		`id, regioncode, isauroraiooptimizationmode, databaseengine, ondemandprice` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`regioncode = EXCLUDED.regioncode, isauroraiooptimizationmode = EXCLUDED.isauroraiooptimizationmode, databaseengine = EXCLUDED.databaseengine, ondemandprice = EXCLUDED.ondemandprice `
	// run
	logf(sqlstr, aas.ID, aas.Regioncode, aas.Isauroraiooptimizationmode, aas.Databaseengine, aas.Ondemandprice)
	if _, err := db.ExecContext(ctx, sqlstr, aas.ID, aas.Regioncode, aas.Isauroraiooptimizationmode, aas.Databaseengine, aas.Ondemandprice); err != nil {
		return logerror(err)
	}
	// set exists
	aas._exists = true
	return nil
}

// Delete deletes the [AwsAuroraServerless] from the database.
func (aas *AwsAuroraServerless) Delete(ctx context.Context, db DB) error {
	switch {
	case !aas._exists: // doesn't exist
		return nil
	case aas._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.aws_aurora_serverlesses ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, aas.ID)
	if _, err := db.ExecContext(ctx, sqlstr, aas.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	aas._deleted = true
	return nil
}

// AwsAuroraServerlessByID retrieves a row from 'public.aws_aurora_serverlesses' as a [AwsAuroraServerless].
//
// Generated from index 'aws_aurora_serverlesses_pkey'.
func AwsAuroraServerlessByID(ctx context.Context, db DB, id string) (*AwsAuroraServerless, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, regioncode, isauroraiooptimizationmode, databaseengine, ondemandprice ` +
		`FROM public.aws_aurora_serverlesses ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	aas := AwsAuroraServerless{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&aas.ID, &aas.Regioncode, &aas.Isauroraiooptimizationmode, &aas.Databaseengine, &aas.Ondemandprice); err != nil {
		return nil, logerror(err)
	}
	return &aas, nil
}
